version: "{build}"
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true
build_script:
  - ps: .\build.ps1
test: off
artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/eshva-public/api/v2/package
    api_key:
      secure: eGX5aim+j0FX2y9WtOeXLK0+abWbSQK7kuXY6WkQ9mWzHhuoqT4DNTWHEVOeTdv7
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    name: production
    skip_symbols: true
    api_key:
      secure: RwdsEIjhYDeJvFbfTZayjLHBWtVTmvwBwfKIiGWG+K7edtQ94Hd5lOuN9yvhG7oF
    on:
      appveyor_repo_tag: true
